"""create wallet model

Revision ID: 1c441dcdd629
Revises: 7419899d42d9
Create Date: 2026-03-29 14:46:02.741459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c441dcdd629'
down_revision: Union[str, Sequence[str], None] = '7419899d42d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('username', postgresql.CITEXT(), nullable=False),
    sa.CheckConstraint('length(username) >= 3 AND length(username) <= 32', name=op.f('ck_users_username_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username')),
    schema='clean_backend'
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['clean_backend.users.id'], name=op.f('fk_wallets_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_wallets')),
    schema='clean_backend'
    )
    op.create_index(op.f('ix_clean_backend_wallets_user_id'), 'wallets', ['user_id'], unique=False, schema='clean_backend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clean_backend_wallets_user_id'), table_name='wallets', schema='clean_backend')
    op.drop_table('wallets', schema='clean_backend')
    op.drop_table('users', schema='clean_backend')
    # ### end Alembic commands ###
